### PR TITLE
Update to PureScript 0.15

### PR DESCRIPTION
**Pull request by CarstenKoenig**
- package-set psc-0.15
- ESM style FFI modules
- fixed type-error in `Test/App.purs/Main`

### CODE REVIEW

**Comment by CarstenKoenig** [comment]
Sorry missed some tests - one moment...

**Comment by CarstenKoenig** [comment]
Hi - there are a few problems left - mainly with the tests and with examples.

The performance tests are compiling but both test time-out after 30sec. - to be honest: I have no idea why - any hints?

The other issue is that the examples seem to import halogen-storybook so I guess I'll have to look at converting this first - I'll try my luck tomorrow.

**Comment by CarstenKoenig** [comment]
seems for me puppeteer is not working (it does not launch a browser) on my machine
it's probably because I have a more or less non-standard chrome installation (it's installed via AUR into /opt/google/chrome and by default not in path ... adding it does not help though)

I'm looking into it but I guess if the examples would compile this would probably work in CI.

storybook is quite old and I think not actively maintained - any thought on if I could drop this example?

**Comment by CarstenKoenig** [comment]
Turns out there seems to be an issue with the way `test.js` is bundled.

The output if just flat functions declarations and one of those is

```
// output/Web.HTML.Window/foreign.js
function document(window2) {
  return function() {
    return window2.document;
  };
}
```

which will fail in a browser (there is already a top-level document): 

```
Uncaught SyntaxError: Identifier 'document' has already been declared
    at test.js:1:1`
```

is there a way to use something like [global name](https://esbuild.github.io/api/#global-name) with `spago bundle-app`?

**Comment by CarstenKoenig** [comment]
I've found a fix for the performance-test (just tell spago to minify the bundled-app so that `document` is renamed) - no idea what to do with the storybook example.

@thomashoneyman any idea?

**Comment by CarstenKoenig** [comment]
Seems I've got it working.

Merging should probably not happen till `halogen-storybook` was upgraded so there is no need to overwrite this dependency any more.

I've queued another [pull request](https://github.com/rnons/purescript-halogen-storybook/pull/11) for that also.

Again sorry for this messy PR :(

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
